<?php

/**
 * @file
 * Used to demonstrate the possibilities of routing in Drupal 8.
 */

/**
 * Implements hook_libraries_info()
 * @return array
 */

//function nognix_libraries_info() {
//  $libraries['responsiveslides'] = array(
//    'name' => 'Responsive Slides',
//    'vendor url' => 'http://responsiveslides.com/',
//    'download url' => 'https://github.com/viljamis/ResponsiveSlides.js',
//    'version' => '1.54',
//    'files' => array(
//      'js' => array('responsiveslides.min.js'),
////        'css' => array('css/mylibrary.css'),
//    ),
//  );
//  return $libraries;
//}

