id: node.search_result
uuid: 96d606c7-198d-49e8-8e02-022cd9a0c59d
label: 'Search result highlighting input'
targetEntityType: node
status: false
cache: true
langcode: und
dependencies:
  module:
    - node
